language: node_js
node_js:
  - 8.7
sudo: required

services:
- mongodb

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ase-grp2-price-paid-data
    region: eu-west-2
    skip_cleanup: true
    local_dir: Project01
    upload-dir: travis
    detect_encoding: true
    on:
      repo: SoftwareEngineeringG02/Project01
      all_branches: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ase-grp2-price-paid-data
    key: travis/AdvSEAPP.zip
    bundle_type: zip
    application: advse-project01
    deployment_group: travisgroup
    region: eu-west-2
    on:
      repo: SoftwareEngineeringG02/Project01
      all_branches: true

script:
  - ls
  - zip -r AdvSEAPP *
  - mkdir -p Project01
  - mv AdvSEAPP.zip Project01/AdvSEAPP.zip

notifications:
  slack: $SLACK_CHANNEL

after_deploy:
  - yum install git
  - ls
  - cd server
  - ./install.sh
  - npm install
  - chmod 764 ../newrelic.sh
  - ../newrelic.sh $NR_APP $NR_LICENSE
  - ls
